workflows:
  android-workflow:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build APK
        script: |
          flutter build apk --release --split-per-abi
      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com

  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jankiagrotourism.app
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
